# -*- coding: utf-8 -*-
"""Handwritten Digit Recognition using Neural Network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arsXfTbHhubT4TmZzH-UfYm1dmOK_Yp-

# Handwritten Digit Recognition using Neural Network

Handwritten digit recognition using MNIST dataset is a major project made with the help of Neural Network. It basically detects the scanned images of handwritten digits.

I have taken this a step further where our handwritten digit recognition system not only detects scanned images of handwritten digits but also allows writing digits on the screen with the help of an integrated GUI for recognition.

Extract the data from mnist-original.mat file

### Import Libraries
"""

from scipy.io import loadmat
import numpy as np
from scipy.optimize import minimize

"""### Loading The Mat File"""

from google.colab import files
uploaded = files.upload()

import scipy.io
import pandas as pd
import matplotlib.pyplot as plt
# Load the .mat file
mat = scipy.io.loadmat('mnist-original.mat')

# The data is typically stored in the 'data' key
data = mat['data']

# The data is usually flattened, so we need to reshape it to view it as an image
# MNIST images are 28x28 pixels
image_data = np.reshape(data[:, 0], (28, 28))

# Display the first image
plt.imshow(image_data, cmap='gray')
plt.show()

# Now let's display the second image
image_data = np.reshape(data[:, 1], (28, 28))
plt.imshow(image_data, cmap='gray')
plt.show()

"""### Extracting Features from mat file"""

X = mat['data']
X =X.transpose()

# Normalizing the data
X = X /255

# Extracting Lbles from Mat file
y = mat['label']
y = y.flatten()

"""### Spliting data into Traning set with 60, 000"""

X_train = X[:60000, :]
y_train = y[:60000]

"""### Spliting data into testing set 10,000"""

X_test = X[60000: , :]
y_test = y[60000:]

m = X.shape[0]

input_layer_size = 784 # Images are of 28 x 28 px so there will be 784 features
hidden_layer_size = 100
num_labels = 10 # there are 10 classes [0 , 9]

# Randomly Initializing Thetas
initial_Theta1 = initialise(hidden_layer_size, input_layer_size)
initialize_Theta2 = initialise(num_labels, hidden_layer_size)

"""# Unrolling prameters into a single column vector"""



